language: dart

dart:
# This won't build on the stable release till it supports nnbd, but 2.12 isn't release yet
#- 2.12
- dev

dart_task:
- test
- dartanalyzer: --fatal-warnings --fatal-lints .

matrix:
  include:
  # Only validate formatting using the dev release
  - dart: dev
    dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
  - $HOME/.pub-cache
