name: gviz
description: Utilities for creating GraphViz graphs.
version: 0.2.0+1
homepage: https://github.com/kevmoo/gviz
author: Kevin Moore <github@j832.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  collection: ^1.14.3

dev_dependencies:
  test: ^1.3.0
